import type {
  Product,
  ProductReview,
  FaqItem,
  RepairService,
  FinancingPlan,
  TeamMember,
  DeviceCategory,
} from "@/lib/types";
import { CATEGORY_META } from "@/lib/category-meta";
import { slugify } from "@/lib/utils";

type RawProduct = Omit<Product, "id" | "slug" | "gradient" | "createdAt" | "rating" | "reviewCount"> & {
  rating: number;
  reviewCount: number;
  daysAgo: number;
};

function daysAgoIso(days: number) {
  const d = new Date();
  d.setDate(d.getDate() - days);
  return d.toISOString();
}

function build(raw: RawProduct): Product {
  const slug = slugify(`${raw.name} ${raw.selectedStorage ?? raw.storageOptions?.[0] ?? ""}`);
  return {
    ...raw,
    id: slug,
    slug,
    gradient: CATEGORY_META[raw.category].gradient,
    createdAt: daysAgoIso(raw.daysAgo),
  };
}

const RAW_PRODUCTS: RawProduct[] = [
  // ── iPhone ────────────────────────────────────────────────
  {
    name: "iPhone 6S",
    brand: "Apple",
    category: "iPhone",
    tagline: "A dependable classic iPhone, still capable of everyday tasks.",
    description:
      "The iPhone 6S remains a reliable, pocketable option for calls, messaging and light browsing. Fully data-wiped and tested on our 60-point checklist.",
    price: 2399,
    compareAtPrice: 2899,
    condition: "Fair",
    batteryHealth: 78,
    storageOptions: ["16GB", "32GB", "64GB"],
    selectedStorage: "16GB",
    colorOptions: ["Gold", "Silver"],
    selectedColor: "Silver",
    stockQuantity: 8,
    specs: [
      { label: "Display", value: "4.7\" Retina HD" },
      { label: "Chip", value: "A9" },
      { label: "Camera", value: "12MP main" },
      { label: "Battery health", value: "78% of original capacity" },
    ],
    accessoriesIncluded: ["USB-C to Lightning cable", "SIM eject tool", "iConnect certified box & documentation"],
    warrantyDays: 30,
    rating: 4.3,
    reviewCount: 22,
    daysAgo: 95,
  },
  {
    name: "iPhone 6S Plus",
    brand: "Apple",
    category: "iPhone",
    tagline: "The larger-screen classic, tested and ready for daily use.",
    description:
      "A bigger display and longer battery life than the standard 6S, in a well-worn but fully functional certified unit.",
    price: 3199,
    compareAtPrice: 3699,
    condition: "Fair",
    batteryHealth: 79,
    storageOptions: ["16GB", "32GB", "64GB"],
    selectedStorage: "16GB",
    colorOptions: ["Silver", "Space Grey"],
    selectedColor: "Space Grey",
    stockQuantity: 6,
    specs: [
      { label: "Display", value: "5.5\" Retina HD" },
      { label: "Chip", value: "A9" },
      { label: "Camera", value: "12MP main" },
      { label: "Battery health", value: "79% of original capacity" },
    ],
    accessoriesIncluded: ["USB-C to Lightning cable", "SIM eject tool", "iConnect certified box & documentation"],
    warrantyDays: 30,
    rating: 4.3,
    reviewCount: 15,
    daysAgo: 100,
  },
  {
    name: "iPhone 7",
    brand: "Apple",
    category: "iPhone",
    tagline: "A simple, sturdy iPhone that still gets the job done.",
    description:
      "Water-resistant and dependable, the iPhone 7 is a solid low-cost option for anyone who just needs a phone that works.",
    price: 2299,
    compareAtPrice: 2799,
    condition: "Good",
    batteryHealth: 81,
    storageOptions: ["32GB", "128GB", "256GB"],
    selectedStorage: "32GB",
    colorOptions: ["Black", "Silver"],
    selectedColor: "Black",
    stockQuantity: 10,
    specs: [
      { label: "Display", value: "4.7\" Retina HD" },
      { label: "Chip", value: "A10 Fusion" },
      { label: "Camera", value: "12MP main" },
      { label: "Battery health", value: "81% of original capacity" },
    ],
    accessoriesIncluded: ["USB-C to Lightning cable", "SIM eject tool", "iConnect certified box & documentation"],
    warrantyDays: 30,
    rating: 4.4,
    reviewCount: 31,
    daysAgo: 85,
  },
  {
    name: "iPhone 7 Plus",
    brand: "Apple",
    category: "iPhone",
    tagline: "Dual cameras and solid everyday performance at a low entry price.",
    description:
      "The first iPhone with dual rear cameras, still a capable performer for everyday use at a genuinely low price.",
    price: 2999,
    compareAtPrice: 3499,
    condition: "Good",
    batteryHealth: 82,
    storageOptions: ["32GB", "128GB", "256GB"],
    selectedStorage: "32GB",
    colorOptions: ["Rose Gold", "Black"],
    selectedColor: "Black",
    stockQuantity: 7,
    specs: [
      { label: "Display", value: "5.5\" Retina HD" },
      { label: "Chip", value: "A10 Fusion" },
      { label: "Camera", value: "Dual 12MP" },
      { label: "Battery health", value: "82% of original capacity" },
    ],
    accessoriesIncluded: ["USB-C to Lightning cable", "SIM eject tool", "iConnect certified box & documentation"],
    warrantyDays: 30,
    rating: 4.4,
    reviewCount: 19,
    daysAgo: 88,
  },
  {
    name: "iPhone 8",
    brand: "Apple",
    category: "iPhone",
    tagline: "The last of the classic home-button design, fully tested.",
    description:
      "Wireless charging and a faster chip round out the classic iPhone design. Certified, cleaned and ready to go.",
    price: 2999,
    compareAtPrice: 3499,
    condition: "Good",
    batteryHealth: 84,
    storageOptions: ["64GB", "128GB", "256GB"],
    selectedStorage: "64GB",
    colorOptions: ["Gold", "Space Grey"],
    selectedColor: "Gold",
    stockQuantity: 12,
    specs: [
      { label: "Display", value: "4.7\" Retina HD" },
      { label: "Chip", value: "A11 Bionic" },
      { label: "Camera", value: "12MP main" },
      { label: "Battery health", value: "84% of original capacity" },
    ],
    accessoriesIncluded: ["USB-C to Lightning cable", "SIM eject tool", "iConnect certified box & documentation"],
    warrantyDays: 30,
    rating: 4.5,
    reviewCount: 27,
    daysAgo: 70,
  },
  {
    name: "iPhone 8 Plus",
    brand: "Apple",
    category: "iPhone",
    tagline: "A bigger classic-design iPhone with dual rear cameras.",
    description:
      "Dual cameras and a larger display, with wireless charging built in. A dependable, well-tested certified unit.",
    price: 4099,
    compareAtPrice: 4799,
    condition: "Good",
    batteryHealth: 83,
    storageOptions: ["64GB", "256GB"],
    selectedStorage: "64GB",
    colorOptions: ["Gold", "Silver"],
    selectedColor: "Silver",
    stockQuantity: 9,
    specs: [
      { label: "Display", value: "5.5\" Retina HD" },
      { label: "Chip", value: "A11 Bionic" },
      { label: "Camera", value: "Dual 12MP" },
      { label: "Battery health", value: "83% of original capacity" },
    ],
    accessoriesIncluded: ["USB-C to Lightning cable", "SIM eject tool", "iConnect certified box & documentation"],
    warrantyDays: 30,
    rating: 4.4,
    reviewCount: 18,
    daysAgo: 75,
  },
  {
    name: "iPhone X",
    brand: "Apple",
    category: "iPhone",
    tagline: "The iPhone that introduced Face ID and an edge-to-edge display.",
    description:
      "A genuine design milestone — OLED display, Face ID and no home button. Tested and certified with fresh diagnostics.",
    price: 5099,
    compareAtPrice: 5999,
    condition: "Good",
    batteryHealth: 82,
    storageOptions: ["64GB", "256GB"],
    selectedStorage: "64GB",
    colorOptions: ["Silver", "Space Grey"],
    selectedColor: "Space Grey",
    stockQuantity: 6,
    specs: [
      { label: "Display", value: "5.8\" Super Retina OLED" },
      { label: "Chip", value: "A11 Bionic" },
      { label: "Camera", value: "Dual 12MP" },
      { label: "Battery health", value: "82% of original capacity" },
    ],
    accessoriesIncluded: ["USB-C to Lightning cable", "SIM eject tool", "iConnect certified box & documentation"],
    warrantyDays: 30,
    rating: 4.5,
    reviewCount: 24,
    daysAgo: 65,
  },
  {
    name: "iPhone XR",
    brand: "Apple",
    category: "iPhone",
    tagline: "A colourful, capable iPhone that remains excellent value.",
    description:
      "Face ID and a big, bright LCD display in Apple's most popular colourway lineup. Great everyday value, fully certified.",
    price: 4799,
    compareAtPrice: 5599,
    condition: "Excellent",
    batteryHealth: 87,
    storageOptions: ["64GB", "128GB", "256GB"],
    selectedStorage: "64GB",
    colorOptions: ["Blue", "White"],
    selectedColor: "Blue",
    stockQuantity: 14,
    specs: [
      { label: "Display", value: "6.1\" Liquid Retina LCD" },
      { label: "Chip", value: "A12 Bionic" },
      { label: "Camera", value: "12MP main" },
      { label: "Battery health", value: "87% of original capacity" },
    ],
    accessoriesIncluded: ["USB-C to Lightning cable", "SIM eject tool", "iConnect certified box & documentation"],
    warrantyDays: 30,
    rating: 4.6,
    reviewCount: 45,
    daysAgo: 55,
  },
  {
    name: "iPhone XS",
    brand: "Apple",
    category: "iPhone",
    tagline: "A compact iPhone with dual cameras and solid everyday speed.",
    description:
      "OLED display and dual cameras in a compact frame. Tested end to end and backed by our 30-day warranty.",
    price: 5299,
    compareAtPrice: 6199,
    condition: "Good",
    batteryHealth: 85,
    storageOptions: ["64GB", "256GB"],
    selectedStorage: "64GB",
    colorOptions: ["Gold", "Silver"],
    selectedColor: "Gold",
    stockQuantity: 8,
    specs: [
      { label: "Display", value: "5.8\" Super Retina OLED" },
      { label: "Chip", value: "A12 Bionic" },
      { label: "Camera", value: "Dual 12MP" },
      { label: "Battery health", value: "85% of original capacity" },
    ],
    accessoriesIncluded: ["USB-C to Lightning cable", "SIM eject tool", "iConnect certified box & documentation"],
    warrantyDays: 30,
    rating: 4.5,
    reviewCount: 21,
    daysAgo: 60,
  },
  {
    name: "iPhone XS Max",
    brand: "Apple",
    category: "iPhone",
    tagline: "The larger-screen XS, certified and ready for daily use.",
    description:
      "The biggest display Apple offered in 2018, paired with dual cameras and solid everyday performance.",
    price: 6299,
    compareAtPrice: 7299,
    condition: "Excellent",
    batteryHealth: 86,
    storageOptions: ["64GB", "256GB"],
    selectedStorage: "64GB",
    colorOptions: ["Silver", "Space Grey"],
    selectedColor: "Silver",
    stockQuantity: 7,
    specs: [
      { label: "Display", value: "6.5\" Super Retina OLED" },
      { label: "Chip", value: "A12 Bionic" },
      { label: "Camera", value: "Dual 12MP" },
      { label: "Battery health", value: "86% of original capacity" },
    ],
    accessoriesIncluded: ["USB-C to Lightning cable", "SIM eject tool", "iConnect certified box & documentation"],
    warrantyDays: 30,
    rating: 4.6,
    reviewCount: 20,
    daysAgo: 58,
  },
  {
    name: "iPhone 11",
    brand: "Apple",
    category: "iPhone",
    tagline: "Dual cameras and all-day battery life at an accessible price.",
    description:
      "One of the most popular iPhones ever made — dual cameras, strong battery life, and a genuinely low certified price.",
    price: 5999,
    compareAtPrice: 6999,
    condition: "Excellent",
    batteryHealth: 89,
    storageOptions: ["64GB", "128GB", "256GB"],
    selectedStorage: "64GB",
    colorOptions: ["Black", "White"],
    selectedColor: "White",
    stockQuantity: 16,
    specs: [
      { label: "Display", value: "6.1\" Liquid Retina LCD" },
      { label: "Chip", value: "A13 Bionic" },
      { label: "Camera", value: "Dual 12MP" },
      { label: "Battery health", value: "89% of original capacity" },
    ],
    accessoriesIncluded: ["USB-C to Lightning cable", "SIM eject tool", "iConnect certified box & documentation"],
    warrantyDays: 30,
    rating: 4.7,
    reviewCount: 58,
    daysAgo: 50,
  },
  {
    name: "iPhone 11 Pro",
    brand: "Apple",
    category: "iPhone",
    tagline: "A pocketable Pro with triple rear cameras.",
    description:
      "Apple's first triple-camera system, in a compact OLED body. Fully certified with fresh battery diagnostics.",
    price: 7499,
    compareAtPrice: 8699,
    condition: "Excellent",
    batteryHealth: 88,
    storageOptions: ["64GB", "256GB"],
    selectedStorage: "64GB",
    colorOptions: ["Midnight Green", "Silver"],
    selectedColor: "Midnight Green",
    stockQuantity: 9,
    specs: [
      { label: "Display", value: "5.8\" Super Retina XDR OLED" },
      { label: "Chip", value: "A13 Bionic" },
      { label: "Camera", value: "Triple 12MP" },
      { label: "Battery health", value: "88% of original capacity" },
    ],
    accessoriesIncluded: ["USB-C to Lightning cable", "SIM eject tool", "iConnect certified box & documentation"],
    warrantyDays: 30,
    rating: 4.6,
    reviewCount: 30,
    daysAgo: 52,
  },
  {
    name: "iPhone 11 Pro Max",
    brand: "Apple",
    category: "iPhone",
    tagline: "Pro-level cameras on the biggest screen of its generation.",
    description:
      "The largest, longest-lasting iPhone 11, with the same triple-camera system as the 11 Pro. Certified and warrantied.",
    price: 8999,
    compareAtPrice: 10499,
    condition: "Excellent",
    batteryHealth: 87,
    storageOptions: ["64GB", "256GB"],
    selectedStorage: "64GB",
    colorOptions: ["Gold", "Space Grey"],
    selectedColor: "Gold",
    stockQuantity: 6,
    specs: [
      { label: "Display", value: "6.5\" Super Retina XDR OLED" },
      { label: "Chip", value: "A13 Bionic" },
      { label: "Camera", value: "Triple 12MP" },
      { label: "Battery health", value: "87% of original capacity" },
    ],
    accessoriesIncluded: ["USB-C to Lightning cable", "SIM eject tool", "iConnect certified box & documentation"],
    warrantyDays: 30,
    rating: 4.7,
    reviewCount: 25,
    daysAgo: 48,
  },
  {
    name: "iPhone SE (2020)",
    brand: "Apple",
    category: "iPhone",
    tagline: "Compact, fast, and built around a familiar design.",
    description:
      "The A13 Bionic chip in a compact, affordable body. A dependable choice for anyone who prefers a smaller phone.",
    price: 3799,
    compareAtPrice: 4499,
    condition: "Good",
    batteryHealth: 85,
    storageOptions: ["64GB", "128GB"],
    selectedStorage: "64GB",
    colorOptions: ["Black", "White"],
    selectedColor: "Black",
    stockQuantity: 11,
    specs: [
      { label: "Display", value: "4.7\" Retina HD" },
      { label: "Chip", value: "A13 Bionic" },
      { label: "Camera", value: "12MP main" },
      { label: "Battery health", value: "85% of original capacity" },
    ],
    accessoriesIncluded: ["USB-C to Lightning cable", "SIM eject tool", "iConnect certified box & documentation"],
    warrantyDays: 30,
    rating: 4.5,
    reviewCount: 29,
    daysAgo: 66,
  },
  {
    name: "iPhone 12",
    brand: "Apple",
    category: "iPhone",
    tagline: "5G speed in Apple's refined flat-edge design.",
    description:
      "The design that defined the modern iPhone look, with 5G and Ceramic Shield durability. Fully certified.",
    price: 7099,
    compareAtPrice: 8299,
    condition: "Excellent",
    batteryHealth: 90,
    storageOptions: ["64GB", "128GB", "256GB"],
    selectedStorage: "64GB",
    colorOptions: ["Blue", "White"],
    selectedColor: "Blue",
    stockQuantity: 13,
    specs: [
      { label: "Display", value: "6.1\" Super Retina XDR OLED" },
      { label: "Chip", value: "A14 Bionic" },
      { label: "Camera", value: "Dual 12MP" },
      { label: "Battery health", value: "90% of original capacity" },
    ],
    accessoriesIncluded: ["USB-C to Lightning cable", "SIM eject tool", "iConnect certified box & documentation"],
    warrantyDays: 30,
    rating: 4.7,
    reviewCount: 41,
    daysAgo: 40,
  },
  {
    name: "iPhone 12 Mini",
    brand: "Apple",
    category: "iPhone",
    tagline: "Full flagship performance in a genuinely compact body.",
    description:
      "All the speed and camera quality of the iPhone 12, shrunk into Apple's smallest recent design.",
    price: 6499,
    compareAtPrice: 7599,
    condition: "Excellent",
    batteryHealth: 89,
    storageOptions: ["64GB", "128GB", "256GB"],
    selectedStorage: "64GB",
    colorOptions: ["Purple", "Blue"],
    selectedColor: "Purple",
    stockQuantity: 8,
    specs: [
      { label: "Display", value: "5.4\" Super Retina XDR OLED" },
      { label: "Chip", value: "A14 Bionic" },
      { label: "Camera", value: "Dual 12MP" },
      { label: "Battery health", value: "89% of original capacity" },
    ],
    accessoriesIncluded: ["USB-C to Lightning cable", "SIM eject tool", "iConnect certified box & documentation"],
    warrantyDays: 30,
    rating: 4.6,
    reviewCount: 22,
    daysAgo: 44,
  },
  {
    name: "iPhone 12 Pro",
    brand: "Apple",
    category: "iPhone",
    tagline: "Pro cameras and Ceramic Shield durability, certified and tested.",
    description:
      "A triple-camera Pro system with LiDAR scanning, in Apple's toughened Ceramic Shield glass. Fully diagnosed and certified.",
    price: 9799,
    compareAtPrice: 11499,
    condition: "Excellent",
    batteryHealth: 90,
    storageOptions: ["128GB", "256GB"],
    selectedStorage: "128GB",
    colorOptions: ["Pacific Blue", "Silver"],
    selectedColor: "Pacific Blue",
    stockQuantity: 7,
    specs: [
      { label: "Display", value: "6.1\" Super Retina XDR OLED" },
      { label: "Chip", value: "A14 Bionic" },
      { label: "Camera", value: "Triple 12MP + LiDAR" },
      { label: "Battery health", value: "90% of original capacity" },
    ],
    accessoriesIncluded: ["USB-C to Lightning cable", "SIM eject tool", "iConnect certified box & documentation"],
    warrantyDays: 30,
    rating: 4.7,
    reviewCount: 26,
    daysAgo: 38,
  },
  {
    name: "iPhone 12 Pro Max",
    brand: "Apple",
    category: "iPhone",
    tagline: "The largest-screen 12, with the full Pro camera system.",
    description:
      "The biggest display and longest battery life of the 12 line-up, with the complete triple-camera Pro system.",
    price: 10799,
    compareAtPrice: 12699,
    condition: "Excellent",
    batteryHealth: 89,
    storageOptions: ["128GB", "256GB"],
    selectedStorage: "128GB",
    colorOptions: ["Graphite", "Gold"],
    selectedColor: "Graphite",
    stockQuantity: 5,
    specs: [
      { label: "Display", value: "6.7\" Super Retina XDR OLED" },
      { label: "Chip", value: "A14 Bionic" },
      { label: "Camera", value: "Triple 12MP + LiDAR" },
      { label: "Battery health", value: "89% of original capacity" },
    ],
    accessoriesIncluded: ["USB-C to Lightning cable", "SIM eject tool", "iConnect certified box & documentation"],
    warrantyDays: 30,
    rating: 4.7,
    reviewCount: 23,
    daysAgo: 36,
  },
  {
    name: "iPhone SE (2022)",
    brand: "Apple",
    category: "iPhone",
    tagline: "A compact iPhone with 5G and modern performance.",
    description:
      "The A15 Bionic chip and 5G in Apple's compact, familiar form factor. A great value pick, fully certified.",
    price: 6199,
    compareAtPrice: 7299,
    condition: "Excellent",
    batteryHealth: 92,
    storageOptions: ["64GB", "128GB"],
    selectedStorage: "64GB",
    colorOptions: ["Midnight", "Red"],
    selectedColor: "Midnight",
    stockQuantity: 15,
    specs: [
      { label: "Display", value: "4.7\" Retina HD" },
      { label: "Chip", value: "A15 Bionic" },
      { label: "Camera", value: "12MP main" },
      { label: "Battery health", value: "92% of original capacity" },
    ],
    accessoriesIncluded: ["USB-C to Lightning cable", "SIM eject tool", "iConnect certified box & documentation"],
    warrantyDays: 30,
    rating: 4.6,
    reviewCount: 33,
    daysAgo: 42,
  },
  {
    name: "iPhone 13",
    brand: "Apple",
    category: "iPhone",
    tagline: "A faster chip and longer battery life in a familiar, loved design.",
    description:
      "One of the most reliable iPhones ever made, with a smaller notch and noticeably longer battery life than the 12.",
    price: 9799,
    compareAtPrice: 11499,
    condition: "Excellent",
    batteryHealth: 91,
    storageOptions: ["128GB", "256GB"],
    selectedStorage: "128GB",
    colorOptions: ["Pink", "Blue"],
    selectedColor: "Blue",
    stockQuantity: 14,
    specs: [
      { label: "Display", value: "6.1\" Super Retina XDR OLED" },
      { label: "Chip", value: "A15 Bionic" },
      { label: "Camera", value: "Dual 12MP" },
      { label: "Battery health", value: "91% of original capacity" },
    ],
    accessoriesIncluded: ["USB-C to Lightning cable", "SIM eject tool", "iConnect certified box & documentation"],
    warrantyDays: 30,
    isFeatured: true,
    rating: 4.8,
    reviewCount: 47,
    daysAgo: 30,
  },
  {
    name: "iPhone 13 Mini",
    brand: "Apple",
    category: "iPhone",
    tagline: "Full iPhone 13 performance in Apple's smallest recent frame.",
    description:
      "The same A15 chip and dual-camera system as the 13, in a genuinely pocketable size for those who want it small.",
    price: 8399,
    compareAtPrice: 9799,
    condition: "Excellent",
    batteryHealth: 90,
    storageOptions: ["128GB", "256GB"],
    selectedStorage: "128GB",
    colorOptions: ["Starlight", "Midnight"],
    selectedColor: "Starlight",
    stockQuantity: 7,
    specs: [
      { label: "Display", value: "5.4\" Super Retina XDR OLED" },
      { label: "Chip", value: "A15 Bionic" },
      { label: "Camera", value: "Dual 12MP" },
      { label: "Battery health", value: "90% of original capacity" },
    ],
    accessoriesIncluded: ["USB-C to Lightning cable", "SIM eject tool", "iConnect certified box & documentation"],
    warrantyDays: 30,
    rating: 4.6,
    reviewCount: 18,
    daysAgo: 34,
  },
  {
    name: "iPhone 13 Pro",
    brand: "Apple",
    category: "iPhone",
    tagline: "ProMotion smoothness and a serious triple-camera system.",
    description:
      "A 120Hz ProMotion display and a genuinely capable triple-camera system. One of our most thoroughly certified units.",
    price: 12799,
    compareAtPrice: 14999,
    condition: "Pristine",
    batteryHealth: 93,
    storageOptions: ["128GB", "256GB"],
    selectedStorage: "128GB",
    colorOptions: ["Sierra Blue", "Graphite"],
    selectedColor: "Sierra Blue",
    stockQuantity: 9,
    specs: [
      { label: "Display", value: "6.1\" Super Retina XDR ProMotion OLED" },
      { label: "Chip", value: "A15 Bionic" },
      { label: "Camera", value: "Triple 12MP" },
      { label: "Battery health", value: "93% of original capacity" },
    ],
    accessoriesIncluded: ["USB-C to Lightning cable", "SIM eject tool", "iConnect certified box & documentation"],
    warrantyDays: 30,
    isFeatured: true,
    rating: 4.8,
    reviewCount: 24,
    daysAgo: 28,
  },
  {
    name: "iPhone 13 Pro Max",
    brand: "Apple",
    category: "iPhone",
    tagline: "The biggest screen, battery and camera system of the 13 line-up.",
    description:
      "ProMotion, the longest battery life Apple had shipped at the time, and the full triple-camera Pro system.",
    price: 14899,
    compareAtPrice: 17499,
    condition: "Excellent",
    batteryHealth: 91,
    storageOptions: ["128GB", "256GB"],
    selectedStorage: "128GB",
    colorOptions: ["Alpine Green", "Silver"],
    selectedColor: "Alpine Green",
    stockQuantity: 6,
    specs: [
      { label: "Display", value: "6.7\" Super Retina XDR ProMotion OLED" },
      { label: "Chip", value: "A15 Bionic" },
      { label: "Camera", value: "Triple 12MP" },
      { label: "Battery health", value: "91% of original capacity" },
    ],
    accessoriesIncluded: ["USB-C to Lightning cable", "SIM eject tool", "iConnect certified box & documentation"],
    warrantyDays: 30,
    rating: 4.8,
    reviewCount: 21,
    daysAgo: 26,
  },
  {
    name: "iPhone 14",
    brand: "Apple",
    category: "iPhone",
    tagline: "A refined, dependable iPhone ready for daily life.",
    description:
      "Reliable, fast, and certified with our full 60-point inspection. A dependable daily driver at a genuinely fair price.",
    price: 11699,
    compareAtPrice: 13699,
    condition: "Excellent",
    batteryHealth: 92,
    storageOptions: ["128GB", "256GB"],
    selectedStorage: "128GB",
    colorOptions: ["Midnight", "Blue"],
    selectedColor: "Midnight",
    stockQuantity: 12,
    specs: [
      { label: "Display", value: "6.1\" Super Retina XDR OLED" },
      { label: "Chip", value: "A15 Bionic" },
      { label: "Camera", value: "Dual 12MP" },
      { label: "Battery health", value: "92% of original capacity" },
    ],
    accessoriesIncluded: ["USB-C to Lightning cable", "SIM eject tool", "iConnect certified box & documentation"],
    warrantyDays: 30,
    rating: 4.7,
    reviewCount: 35,
    daysAgo: 20,
  },
  {
    name: "iPhone 14 Pro",
    brand: "Apple",
    category: "iPhone",
    tagline: "Dynamic Island and Pro-grade cameras, certified and tested.",
    description:
      "The Pro camera system and Dynamic Island, in great condition and backed by our 30-day warranty.",
    price: 13199,
    compareAtPrice: 15499,
    condition: "Pristine",
    batteryHealth: 94,
    storageOptions: ["128GB", "256GB"],
    selectedStorage: "128GB",
    colorOptions: ["Deep Purple", "Space Black"],
    selectedColor: "Deep Purple",
    stockQuantity: 8,
    specs: [
      { label: "Display", value: "6.1\" Super Retina XDR ProMotion OLED, Dynamic Island" },
      { label: "Chip", value: "A16 Bionic" },
      { label: "Camera", value: "Triple 48MP" },
      { label: "Battery health", value: "94% of original capacity" },
    ],
    accessoriesIncluded: ["USB-C to Lightning cable", "SIM eject tool", "iConnect certified box & documentation"],
    warrantyDays: 30,
    rating: 4.8,
    reviewCount: 28,
    daysAgo: 18,
  },
  {
    name: "iPhone 14 Pro Max",
    brand: "Apple",
    category: "iPhone",
    tagline: "The most capable 14, with the largest display and battery.",
    description:
      "Dynamic Island, the 48MP Pro camera system, and Apple's longest 14-series battery life, fully certified.",
    price: 15599,
    compareAtPrice: 18299,
    condition: "Excellent",
    batteryHealth: 93,
    storageOptions: ["128GB", "256GB"],
    selectedStorage: "128GB",
    colorOptions: ["Gold", "Silver"],
    selectedColor: "Gold",
    stockQuantity: 6,
    specs: [
      { label: "Display", value: "6.7\" Super Retina XDR ProMotion OLED, Dynamic Island" },
      { label: "Chip", value: "A16 Bionic" },
      { label: "Camera", value: "Triple 48MP" },
      { label: "Battery health", value: "93% of original capacity" },
    ],
    accessoriesIncluded: ["USB-C to Lightning cable", "SIM eject tool", "iConnect certified box & documentation"],
    warrantyDays: 30,
    rating: 4.8,
    reviewCount: 19,
    daysAgo: 16,
  },
  {
    name: "iPhone 15",
    brand: "Apple",
    category: "iPhone",
    tagline: "Dynamic Island and a 48MP camera, now with USB-C.",
    description:
      "Dynamic Island, a 48MP main camera and USB-C, in a colour-infused glass and aluminium design. Fully certified.",
    price: 15599,
    compareAtPrice: 18299,
    condition: "Excellent",
    batteryHealth: 95,
    storageOptions: ["128GB", "256GB"],
    selectedStorage: "128GB",
    colorOptions: ["Pink", "Black"],
    selectedColor: "Black",
    stockQuantity: 11,
    specs: [
      { label: "Display", value: "6.1\" Super Retina XDR OLED, Dynamic Island" },
      { label: "Chip", value: "A16 Bionic" },
      { label: "Camera", value: "48MP main + 12MP ultra-wide" },
      { label: "Battery health", value: "95% of original capacity" },
    ],
    accessoriesIncluded: ["USB-C cable", "SIM eject tool", "iConnect certified box & documentation"],
    warrantyDays: 30,
    rating: 4.8,
    reviewCount: 29,
    daysAgo: 14,
  },
  {
    name: "iPhone 15 Pro",
    brand: "Apple",
    category: "iPhone",
    tagline: "A titanium design with A17 Pro speed and serious camera power.",
    description:
      "A serious camera system in a refined titanium frame. Tested and certified with full battery diagnostics before it ever reaches you.",
    price: 20599,
    compareAtPrice: 24199,
    condition: "Excellent",
    batteryHealth: 96,
    storageOptions: ["128GB", "256GB"],
    selectedStorage: "128GB",
    colorOptions: ["Natural Titanium", "White Titanium"],
    selectedColor: "White Titanium",
    stockQuantity: 7,
    specs: [
      { label: "Display", value: "6.1\" Super Retina XDR ProMotion OLED" },
      { label: "Chip", value: "A17 Pro" },
      { label: "Camera", value: "48MP main + 12MP ultra-wide + 12MP telephoto" },
      { label: "Battery health", value: "96% of original capacity" },
    ],
    accessoriesIncluded: ["USB-C cable", "SIM eject tool", "iConnect certified box & documentation"],
    warrantyDays: 30,
    rating: 4.9,
    reviewCount: 22,
    daysAgo: 12,
  },
  {
    name: "iPhone 15 Pro Max",
    brand: "Apple",
    category: "iPhone",
    tagline: "Our top-tier certified iPhone — titanium build and the longest zoom in the line-up.",
    description:
      "The iPhone 15 Pro Max in a titanium design, with the A17 Pro chip and the most advanced Pro camera system yet. Every unit is data-wiped, functionally tested on 60+ points, and graded honestly.",
    price: 23999,
    compareAtPrice: 27999,
    condition: "Pristine",
    batteryHealth: 96,
    storageOptions: ["256GB"],
    selectedStorage: "256GB",
    colorOptions: ["Natural Titanium", "Blue Titanium", "Black Titanium"],
    selectedColor: "Natural Titanium",
    stockQuantity: 6,
    specs: [
      { label: "Display", value: "6.7\" Super Retina XDR ProMotion OLED" },
      { label: "Chip", value: "A17 Pro" },
      { label: "Camera", value: "48MP main + 12MP ultra-wide + 12MP telephoto" },
      { label: "Battery health", value: "96% of original capacity" },
    ],
    accessoriesIncluded: ["USB-C cable", "SIM eject tool", "iConnect certified box & documentation"],
    warrantyDays: 30,
    isFeatured: true,
    rating: 4.9,
    reviewCount: 34,
    daysAgo: 6,
  },
  {
    name: "iPhone 16",
    brand: "Apple",
    category: "iPhone",
    tagline: "The newest generation, with Apple's latest chip and camera system.",
    description:
      "Apple's latest-generation iPhone, freshly certified with our full inspection ahead of listing.",
    price: 21499,
    compareAtPrice: 24999,
    condition: "Pristine",
    batteryHealth: 98,
    storageOptions: ["256GB"],
    selectedStorage: "256GB",
    colorOptions: ["Ultramarine", "Teal"],
    selectedColor: "Ultramarine",
    stockQuantity: 9,
    specs: [
      { label: "Display", value: "6.1\" Super Retina XDR OLED" },
      { label: "Chip", value: "A18" },
      { label: "Camera", value: "48MP main + 12MP ultra-wide" },
      { label: "Battery health", value: "98% of original capacity" },
    ],
    accessoriesIncluded: ["USB-C cable", "SIM eject tool", "iConnect certified box & documentation"],
    warrantyDays: 30,
    isNewArrival: true,
    rating: 4.9,
    reviewCount: 14,
    daysAgo: 4,
  },
  {
    name: "iPhone 16 Pro",
    brand: "Apple",
    category: "iPhone",
    tagline: "Refined titanium design with even faster Pro performance.",
    description:
      "A larger display, the A18 Pro chip, and the full titanium Pro camera system. Newly certified stock.",
    price: 27599,
    compareAtPrice: 31999,
    condition: "Pristine",
    batteryHealth: 97,
    storageOptions: ["256GB"],
    selectedStorage: "256GB",
    colorOptions: ["Desert Titanium", "Natural Titanium"],
    selectedColor: "Desert Titanium",
    stockQuantity: 5,
    specs: [
      { label: "Display", value: "6.3\" Super Retina XDR ProMotion OLED" },
      { label: "Chip", value: "A18 Pro" },
      { label: "Camera", value: "Triple 48MP" },
      { label: "Battery health", value: "97% of original capacity" },
    ],
    accessoriesIncluded: ["USB-C cable", "SIM eject tool", "iConnect certified box & documentation"],
    warrantyDays: 30,
    isNewArrival: true,
    rating: 4.9,
    reviewCount: 11,
    daysAgo: 3,
  },
  {
    name: "iPhone 16 Pro Max",
    brand: "Apple",
    category: "iPhone",
    tagline: "The largest, most capable iPhone we sell, fully certified.",
    description:
      "The newest and largest Pro Max, with the full titanium camera system and Apple's longest battery life to date.",
    price: 29999,
    compareAtPrice: 34999,
    condition: "Pristine",
    batteryHealth: 98,
    storageOptions: ["256GB"],
    selectedStorage: "256GB",
    colorOptions: ["Desert Titanium", "Black Titanium"],
    selectedColor: "Black Titanium",
    stockQuantity: 4,
    specs: [
      { label: "Display", value: "6.9\" Super Retina XDR ProMotion OLED" },
      { label: "Chip", value: "A18 Pro" },
      { label: "Camera", value: "Triple 48MP" },
      { label: "Battery health", value: "98% of original capacity" },
    ],
    accessoriesIncluded: ["USB-C cable", "SIM eject tool", "iConnect certified box & documentation"],
    warrantyDays: 30,
    isNewArrival: true,
    rating: 5.0,
    reviewCount: 8,
    daysAgo: 2,
  },
  // ── Samsung Galaxy ───────────────────────────────────────
  {
    name: "Samsung Galaxy S24 Ultra",
    brand: "Samsung",
    category: "Samsung Galaxy",
    tagline: "Galaxy AI is here.",
    description:
      "The S-Pen, a 200MP camera system, and a titanium frame — inspected, cleaned, and certified with a fresh factory reset.",
    price: 21999,
    compareAtPrice: 25999,
    condition: "Pristine",
    batteryHealth: 97,
    storageOptions: ["256GB", "512GB"],
    selectedStorage: "256GB",
    colorOptions: ["Titanium Black", "Titanium Violet"],
    selectedColor: "Titanium Black",
    stockQuantity: 7,
    specs: [
      { label: "Display", value: "6.8\" Dynamic AMOLED 2X, 120Hz" },
      { label: "Chip", value: "Snapdragon 8 Gen 3" },
      { label: "Camera", value: "200MP main + 50MP periscope telephoto" },
      { label: "Battery health", value: "97% of original capacity" },
    ],
    accessoriesIncluded: ["USB-C cable", "S-Pen", "iConnect certified box & documentation"],
    warrantyDays: 30,
    isFeatured: true,
    rating: 4.9,
    reviewCount: 26,
    daysAgo: 9,
  },
  {
    name: "Samsung Galaxy Z Flip 5",
    brand: "Samsung",
    category: "Samsung Galaxy",
    tagline: "Flex your style.",
    description:
      "A genuinely fun foldable with a bigger cover screen. Hinge tested for smooth, consistent fold-and-close action.",
    price: 14999,
    compareAtPrice: 18999,
    condition: "Excellent",
    batteryHealth: 92,
    storageOptions: ["256GB"],
    selectedStorage: "256GB",
    colorOptions: ["Mint", "Graphite"],
    selectedColor: "Mint",
    stockQuantity: 4,
    specs: [
      { label: "Display", value: "6.7\" foldable AMOLED + 3.4\" cover screen" },
      { label: "Chip", value: "Snapdragon 8 Gen 2 for Galaxy" },
      { label: "Camera", value: "12MP main + 12MP ultra-wide" },
      { label: "Battery health", value: "92% of original capacity" },
    ],
    accessoriesIncluded: ["USB-C cable", "iConnect certified box & documentation"],
    warrantyDays: 30,
    isNewArrival: true,
    rating: 4.7,
    reviewCount: 15,
    daysAgo: 5,
  },
  {
    name: "Samsung Galaxy S23",
    brand: "Samsung",
    category: "Samsung Galaxy",
    tagline: "Epic, every day.",
    description:
      "A compact flagship with a superb camera. Light wear on the frame, fully functional, and backed by our warranty.",
    price: 11999,
    compareAtPrice: 14499,
    condition: "Good",
    batteryHealth: 88,
    storageOptions: ["128GB", "256GB"],
    selectedStorage: "128GB",
    colorOptions: ["Phantom Black", "Cream"],
    selectedColor: "Phantom Black",
    stockQuantity: 8,
    specs: [
      { label: "Display", value: "6.1\" Dynamic AMOLED 2X, 120Hz" },
      { label: "Chip", value: "Snapdragon 8 Gen 2 for Galaxy" },
      { label: "Camera", value: "50MP main + 12MP ultra-wide" },
      { label: "Battery health", value: "88% of original capacity" },
    ],
    accessoriesIncluded: ["USB-C cable", "iConnect certified box & documentation"],
    warrantyDays: 30,
    rating: 4.6,
    reviewCount: 33,
    daysAgo: 52,
  },
  {
    name: "Samsung Galaxy A54",
    brand: "Samsung",
    category: "Samsung Galaxy",
    tagline: "Awesome, unlocked.",
    description:
      "A brilliant everyday mid-ranger with a big battery and a bright, punchy display. Excellent value for a first smartphone.",
    price: 6999,
    compareAtPrice: 8499,
    condition: "Excellent",
    batteryHealth: 93,
    storageOptions: ["128GB"],
    selectedStorage: "128GB",
    colorOptions: ["Awesome Graphite", "Awesome Lime"],
    selectedColor: "Awesome Graphite",
    stockQuantity: 13,
    specs: [
      { label: "Display", value: "6.4\" Super AMOLED, 120Hz" },
      { label: "Chip", value: "Exynos 1380" },
      { label: "Camera", value: "50MP main + 12MP ultra-wide" },
      { label: "Battery health", value: "93% of original capacity" },
    ],
    accessoriesIncluded: ["USB-C cable", "iConnect certified box & documentation"],
    warrantyDays: 30,
    rating: 4.5,
    reviewCount: 41,
    daysAgo: 30,
  },

  // ── iPad ──────────────────────────────────────────────────
  {
    name: "iPad Pro 12.9\" (6th Gen)",
    brand: "Apple",
    category: "iPad",
    tagline: "Impossibly advanced.",
    description:
      "The M2 chip and Liquid Retina XDR display make this the most capable iPad we sell. Screen and digitiser fully tested.",
    price: 18999,
    compareAtPrice: 22999,
    condition: "Excellent",
    batteryHealth: 95,
    storageOptions: ["128GB", "256GB"],
    selectedStorage: "256GB",
    colorOptions: ["Space Grey", "Silver"],
    selectedColor: "Space Grey",
    stockQuantity: 5,
    specs: [
      { label: "Display", value: "12.9\" Liquid Retina XDR" },
      { label: "Chip", value: "Apple M2" },
      { label: "Camera", value: "12MP wide + 10MP ultra-wide" },
      { label: "Battery health", value: "95% of original capacity" },
    ],
    accessoriesIncluded: ["USB-C cable", "iConnect certified box & documentation"],
    warrantyDays: 30,
    isFeatured: true,
    rating: 4.8,
    reviewCount: 18,
    daysAgo: 21,
  },
  {
    name: "iPad Air (5th Gen)",
    brand: "Apple",
    category: "iPad",
    tagline: "Serious performance in a light package.",
    description:
      "The M1 chip in a slim, colourful design. A light scuff on one corner, otherwise flawless — priced accordingly.",
    price: 10999,
    compareAtPrice: 13499,
    condition: "Good",
    batteryHealth: 90,
    storageOptions: ["64GB", "256GB"],
    selectedStorage: "64GB",
    colorOptions: ["Blue", "Starlight"],
    selectedColor: "Blue",
    stockQuantity: 9,
    specs: [
      { label: "Display", value: "10.9\" Liquid Retina" },
      { label: "Chip", value: "Apple M1" },
      { label: "Camera", value: "12MP wide" },
      { label: "Battery health", value: "90% of original capacity" },
    ],
    accessoriesIncluded: ["USB-C cable", "iConnect certified box & documentation"],
    warrantyDays: 30,
    rating: 4.7,
    reviewCount: 24,
    daysAgo: 46,
  },
  {
    name: "iPad (10th Gen)",
    brand: "Apple",
    category: "iPad",
    tagline: "Colourful. Capable. All-new design.",
    description:
      "A fresh edge-to-edge design and USB-C, perfect for study, streaming and everyday browsing.",
    price: 7999,
    compareAtPrice: 9999,
    condition: "Excellent",
    batteryHealth: 96,
    storageOptions: ["64GB"],
    selectedStorage: "64GB",
    colorOptions: ["Blue", "Yellow", "Silver"],
    selectedColor: "Silver",
    stockQuantity: 12,
    specs: [
      { label: "Display", value: "10.9\" Liquid Retina" },
      { label: "Chip", value: "A14 Bionic" },
      { label: "Camera", value: "12MP wide" },
      { label: "Battery health", value: "96% of original capacity" },
    ],
    accessoriesIncluded: ["USB-C cable", "iConnect certified box & documentation"],
    warrantyDays: 30,
    isNewArrival: true,
    rating: 4.7,
    reviewCount: 12,
    daysAgo: 4,
  },

  // ── Apple Watch ───────────────────────────────────────────
  {
    name: "Apple Watch Series 9",
    brand: "Apple",
    category: "Apple Watch",
    tagline: "Smarter. Brighter. Mightier.",
    description:
      "Double Tap, a brighter display, and comprehensive health tracking. Screen, crown and sensors all tested.",
    price: 6999,
    compareAtPrice: 8999,
    condition: "Excellent",
    batteryHealth: 91,
    storageOptions: ["45mm GPS"],
    selectedStorage: "45mm GPS",
    colorOptions: ["Midnight", "Starlight"],
    selectedColor: "Midnight",
    stockQuantity: 10,
    specs: [
      { label: "Display", value: "Always-On Retina LTPO OLED" },
      { label: "Chip", value: "S9 SiP" },
      { label: "Health", value: "ECG, blood oxygen, temperature sensing" },
      { label: "Battery health", value: "91% of original capacity" },
    ],
    accessoriesIncluded: ["Magnetic charging cable", "iConnect certified box & documentation"],
    warrantyDays: 30,
    isFeatured: true,
    rating: 4.8,
    reviewCount: 21,
    daysAgo: 27,
  },
  {
    name: "Apple Watch SE (2nd Gen)",
    brand: "Apple",
    category: "Apple Watch",
    tagline: "A great watch. A great price.",
    description:
      "All the essentials — activity tracking, notifications and fall detection — in our most affordable certified Apple Watch.",
    price: 4499,
    compareAtPrice: 5999,
    condition: "Good",
    batteryHealth: 88,
    storageOptions: ["40mm GPS"],
    selectedStorage: "40mm GPS",
    colorOptions: ["Midnight", "Silver"],
    selectedColor: "Silver",
    stockQuantity: 15,
    specs: [
      { label: "Display", value: "Retina OLED" },
      { label: "Chip", value: "S8 SiP" },
      { label: "Health", value: "Heart rate, fall & crash detection" },
      { label: "Battery health", value: "88% of original capacity" },
    ],
    accessoriesIncluded: ["Magnetic charging cable", "iConnect certified box & documentation"],
    warrantyDays: 30,
    isNewArrival: true,
    rating: 4.6,
    reviewCount: 17,
    daysAgo: 8,
  },

  // ── AirPods ───────────────────────────────────────────────
  {
    name: "AirPods Pro (2nd Gen)",
    brand: "Apple",
    category: "AirPods",
    tagline: "Next-level Active Noise Cancellation.",
    description:
      "Case and buds fully cleaned and sanitised, battery cycles verified, fit-tested for consistent seal and sound.",
    price: 3799,
    compareAtPrice: 4999,
    condition: "Pristine",
    storageOptions: ["USB-C case"],
    selectedStorage: "USB-C case",
    stockQuantity: 20,
    specs: [
      { label: "Noise control", value: "Active Noise Cancellation + Transparency" },
      { label: "Chip", value: "Apple H2" },
      { label: "Battery", value: "Up to 6 hrs per charge, 30 hrs with case" },
      { label: "Case", value: "USB-C, MagSafe compatible" },
    ],
    accessoriesIncluded: ["Charging case", "USB-C cable", "3 sizes of ear tips"],
    warrantyDays: 30,
    isFeatured: true,
    rating: 4.9,
    reviewCount: 47,
    daysAgo: 14,
  },
  {
    name: "AirPods Max",
    brand: "Apple",
    category: "AirPods",
    tagline: "Computational audio. Sky high fidelity.",
    description:
      "Over-ear luxury with rich, detailed audio. Ear cushions sanitised and replaced where needed; light marks on the headband.",
    price: 6499,
    compareAtPrice: 8999,
    condition: "Good",
    storageOptions: ["Lightning case"],
    selectedStorage: "Lightning case",
    colorOptions: ["Space Grey", "Silver", "Sky Blue"],
    selectedColor: "Space Grey",
    stockQuantity: 6,
    specs: [
      { label: "Noise control", value: "Active Noise Cancellation + Transparency" },
      { label: "Chip", value: "Apple H1 (dual)" },
      { label: "Battery", value: "Up to 20 hrs per charge" },
      { label: "Build", value: "Stainless steel frame, knit mesh canopy" },
    ],
    accessoriesIncluded: ["Smart Case", "Lightning to USB-C cable"],
    warrantyDays: 30,
    isNewArrival: true,
    rating: 4.7,
    reviewCount: 13,
    daysAgo: 11,
  },

  // ── MacBook ───────────────────────────────────────────────
  {
    name: "MacBook Air M2 13\"",
    brand: "Apple",
    category: "MacBook",
    tagline: "Impressively big. Impossibly thin.",
    description:
      "Fanless, fast, and quiet. Full diagnostic run on battery, keyboard, trackpad, ports and display uniformity.",
    price: 17999,
    compareAtPrice: 21999,
    condition: "Excellent",
    batteryHealth: 92,
    storageOptions: ["256GB", "512GB"],
    selectedStorage: "256GB",
    colorOptions: ["Midnight", "Starlight", "Space Grey"],
    selectedColor: "Midnight",
    stockQuantity: 4,
    specs: [
      { label: "Display", value: "13.6\" Liquid Retina" },
      { label: "Chip", value: "Apple M2, 8-core CPU" },
      { label: "Memory", value: "8GB unified memory" },
      { label: "Battery health", value: "92% of original capacity" },
    ],
    accessoriesIncluded: ["Original 30W USB-C charger & cable", "iConnect certified box & documentation"],
    warrantyDays: 30,
    isFeatured: true,
    rating: 4.9,
    reviewCount: 16,
    daysAgo: 17,
  },
  {
    name: "MacBook Pro 14\" M3",
    brand: "Apple",
    category: "MacBook",
    tagline: "Mind-blowing. Head-turning.",
    description:
      "A Liquid Retina XDR display and pro-grade performance for creative work. One of our most thoroughly tested certifications.",
    price: 28999,
    compareAtPrice: 34999,
    condition: "Pristine",
    batteryHealth: 98,
    storageOptions: ["512GB", "1TB"],
    selectedStorage: "512GB",
    colorOptions: ["Space Black", "Silver"],
    selectedColor: "Space Black",
    stockQuantity: 3,
    specs: [
      { label: "Display", value: "14.2\" Liquid Retina XDR" },
      { label: "Chip", value: "Apple M3, 8-core CPU" },
      { label: "Memory", value: "8GB unified memory" },
      { label: "Battery health", value: "98% of original capacity" },
    ],
    accessoriesIncluded: ["Original 70W USB-C charger & cable", "iConnect certified box & documentation"],
    warrantyDays: 30,
    isNewArrival: true,
    rating: 5.0,
    reviewCount: 9,
    daysAgo: 2,
  },

  // ── Accessories ───────────────────────────────────────────
  {
    name: "Apple 20W USB-C Power Adapter",
    brand: "Apple",
    category: "Accessories",
    tagline: "Fast, compact charging.",
    description: "Genuine Apple 20W adapter, unused surplus stock, sealed for hygiene and tested for output.",
    price: 399,
    compareAtPrice: 549,
    condition: "Pristine",
    stockQuantity: 40,
    specs: [
      { label: "Output", value: "20W USB-C Power Delivery" },
      { label: "Compatibility", value: "iPhone, iPad, AirPods" },
    ],
    accessoriesIncluded: ["Power adapter"],
    warrantyDays: 30,
    rating: 4.8,
    reviewCount: 62,
    daysAgo: 20,
  },
  {
    name: "Apple MagSafe Charger",
    brand: "Apple",
    category: "Accessories",
    tagline: "Effortless wireless charging.",
    description: "Perfectly aligned magnetic wireless charging for iPhone 12 and later. Genuine Apple stock.",
    price: 549,
    compareAtPrice: 749,
    condition: "Pristine",
    stockQuantity: 25,
    specs: [
      { label: "Output", value: "Up to 15W wireless" },
      { label: "Compatibility", value: "iPhone 12 and later" },
    ],
    accessoriesIncluded: ["MagSafe charger", "USB-C cable"],
    warrantyDays: 30,
    isNewArrival: true,
    rating: 4.7,
    reviewCount: 38,
    daysAgo: 7,
  },
  {
    name: "Genuine Leather MagSafe Case — iPhone 15",
    brand: "Apple",
    category: "Accessories",
    tagline: "Slim protection, premium feel.",
    description: "Soft, supple leather with perfect MagSafe alignment. New, boxed stock.",
    price: 699,
    compareAtPrice: 949,
    condition: "Pristine",
    colorOptions: ["Black", "Umber", "Sequoia Green"],
    selectedColor: "Black",
    stockQuantity: 30,
    specs: [
      { label: "Material", value: "Genuine leather" },
      { label: "Compatibility", value: "iPhone 15" },
    ],
    accessoriesIncluded: ["Case"],
    warrantyDays: 30,
    rating: 4.6,
    reviewCount: 27,
    daysAgo: 15,
  },
];

export const PRODUCTS: Product[] = RAW_PRODUCTS.map(build);

export function getProductBySlug(slug: string) {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function getFeaturedProducts() {
  return PRODUCTS.filter((p) => p.isFeatured);
}

export function getNewArrivals() {
  return PRODUCTS.filter((p) => p.isNewArrival);
}

export function getRelatedProducts(product: Product, limit = 4) {
  return PRODUCTS.filter((p) => p.category === product.category && p.id !== product.id).slice(0, limit);
}

export const CATEGORIES: DeviceCategory[] = [
  "iPhone",
  "Samsung Galaxy",
  "iPad",
  "Apple Watch",
  "AirPods",
  "MacBook",
  "Accessories",
];

// ── Reviews (product-level) ───────────────────────────────────
export const PRODUCT_REVIEWS: ProductReview[] = [
  {
    id: "r1",
    productId: "iphone-15-pro-max-256gb",
    author: "Thabo M.",
    location: "Johannesburg",
    rating: 5,
    title: "Genuinely looks brand new",
    body: "I was sceptical about buying a pre-owned Pro Max but honestly can't find a mark on it. Arrived in two days, battery health exactly as listed.",
    verifiedPurchase: true,
    createdAt: daysAgoIso(12),
  },
  {
    id: "r2",
    productId: "iphone-15-pro-max-256gb",
    author: "Aisha K.",
    location: "Cape Town",
    rating: 5,
    title: "Saved thousands, zero compromise",
    body: "The certification report that came with it gave me total confidence. Would buy from iConnect again without hesitation.",
    verifiedPurchase: true,
    createdAt: daysAgoIso(25),
  },
  {
    id: "r3",
    productId: "samsung-galaxy-s24-ultra-256gb",
    author: "Pieter v.d. Merwe",
    location: "Pretoria",
    rating: 5,
    title: "S-Pen and all, flawless",
    body: "Screen is spotless and the S-Pen works perfectly. Delivery tracking kept me updated the whole way.",
    verifiedPurchase: true,
    createdAt: daysAgoIso(19),
  },
  {
    id: "r4",
    productId: "macbook-air-m2-13-256gb",
    author: "Naledi S.",
    location: "Durban",
    rating: 5,
    title: "Perfect for design work",
    body: "Runs Figma and Lightroom without a hiccup. Genuinely couldn't tell it wasn't new out of the box.",
    verifiedPurchase: true,
    createdAt: daysAgoIso(30),
  },
  {
    id: "r5",
    productId: "iphone-14-128gb",
    author: "Kagiso R.",
    location: "Bloemfontein",
    rating: 4,
    title: "Great phone, tiny mark on the back",
    body: "Exactly as described under 'Excellent' — one small mark you'd only notice if you were looking. Battery lasts all day.",
    verifiedPurchase: true,
    createdAt: daysAgoIso(45),
  },
  {
    id: "r6",
    productId: "airpods-pro-2nd-gen-usb-c-case",
    author: "Zanele D.",
    location: "Gqeberha",
    rating: 5,
    title: "Sounded brand new",
    body: "Noise cancelling is as strong as I remember from a friend's brand new pair. Case looked untouched.",
    verifiedPurchase: true,
    createdAt: daysAgoIso(8),
  },
  {
    id: "r7",
    productId: "ipad-pro-12-9-6th-gen-256gb",
    author: "Johan B.",
    location: "Stellenbosch",
    rating: 5,
    title: "Screen is immaculate",
    body: "Was worried about dead pixels or screen burn — nothing. Runs Procreate beautifully.",
    verifiedPurchase: true,
    createdAt: daysAgoIso(22),
  },
  {
    id: "r8",
    productId: "iphone-13-128gb",
    author: "Lindiwe N.",
    location: "East London",
    rating: 4,
    title: "Solid value",
    body: "Battery health was a little lower than I hoped but still easily gets me through a full day. Great price for what it is.",
    verifiedPurchase: true,
    createdAt: daysAgoIso(37),
  },
];

export function getReviewsForProduct(productId: string) {
  return PRODUCT_REVIEWS.filter((r) => r.productId === productId);
}

// ── Homepage testimonials ─────────────────────────────────────
export interface Testimonial {
  id: string;
  author: string;
  location: string;
  rating: 1 | 2 | 3 | 4 | 5;
  quote: string;
  device: string;
}

export const TESTIMONIALS: Testimonial[] = [
  {
    id: "t1",
    author: "Thandiwe P.",
    location: "Johannesburg",
    rating: 5,
    quote:
      "The certification report sold me. Every point they checked was listed out — battery, screen, cameras, buttons. Nothing felt hidden.",
    device: "iPhone 15 Pro",
  },
  {
    id: "t2",
    author: "Ryan C.",
    location: "Cape Town",
    rating: 5,
    quote:
      "Traded in my old MacBook and the quote matched what I was shown online exactly. Credited instantly against my new purchase.",
    device: "MacBook Air M2",
  },
  {
    id: "t3",
    author: "Nomvula K.",
    location: "Durban",
    rating: 5,
    quote: "Delivery was quicker than most brand-new retailers I've ordered from. Beautifully packaged too.",
    device: "iPad Air",
  },
  {
    id: "t4",
    author: "Werner S.",
    location: "Pretoria",
    rating: 4,
    quote: "Financing approval took minutes. Got my Galaxy S24 Ultra the next day without paying it off in one go.",
    device: "Galaxy S24 Ultra",
  },
  {
    id: "t5",
    author: "Buhle M.",
    location: "Gqeberha",
    rating: 5,
    quote: "Sold my old iPhone for cash the same week — the payout landed the day after they received the device.",
    device: "Sold: iPhone 12",
  },
  {
    id: "t6",
    author: "Chloé R.",
    location: "Stellenbosch",
    rating: 5,
    quote: "Screen repair on my Watch was done in under an hour while I waited. Genuinely impressive service.",
    device: "Apple Watch Series 8",
  },
];

// ── Repairs ────────────────────────────────────────────────────
export const REPAIR_SERVICES: RepairService[] = [
  { id: "rp1", device: "iPhone", issue: "Screen replacement", priceFrom: 899, turnaround: "Same day" },
  { id: "rp2", device: "iPhone", issue: "Battery replacement", priceFrom: 549, turnaround: "Same day" },
  { id: "rp3", device: "iPhone", issue: "Back glass replacement", priceFrom: 749, turnaround: "24–48 hrs" },
  { id: "rp4", device: "iPhone", issue: "Charging port repair", priceFrom: 499, turnaround: "Same day" },
  { id: "rp5", device: "Samsung Galaxy", issue: "Screen replacement", priceFrom: 999, turnaround: "24–48 hrs" },
  { id: "rp6", device: "Samsung Galaxy", issue: "Battery replacement", priceFrom: 599, turnaround: "Same day" },
  { id: "rp7", device: "iPad", issue: "Screen & digitiser replacement", priceFrom: 1299, turnaround: "2–3 days" },
  { id: "rp8", device: "Apple Watch", issue: "Screen replacement", priceFrom: 799, turnaround: "Same day" },
  { id: "rp9", device: "MacBook", issue: "Battery replacement", priceFrom: 1599, turnaround: "2–3 days" },
  { id: "rp10", device: "MacBook", issue: "Keyboard / trackpad repair", priceFrom: 1899, turnaround: "3–5 days" },
  { id: "rp11", device: "iPhone", issue: "Water damage diagnostic & repair", priceFrom: 399, turnaround: "24–72 hrs" },
  { id: "rp12", device: "AirPods", issue: "Battery / charging case issue", priceFrom: 449, turnaround: "24–48 hrs" },
];

// ── Financing ──────────────────────────────────────────────────
export const FINANCING_PLANS: FinancingPlan[] = [
  {
    id: "f3",
    months: 3,
    label: "3-month plan",
    interestFree: true,
    description: "Split your purchase into 3 equal, interest-free instalments.",
  },
  {
    id: "f6",
    months: 6,
    label: "6-month plan",
    interestFree: true,
    description: "6 equal instalments with no interest, approved in minutes.",
  },
  {
    id: "f12",
    months: 12,
    label: "12-month plan",
    interestFree: false,
    description: "Lower monthly payments over a full year, low fixed rate.",
  },
  {
    id: "f24",
    months: 24,
    label: "24-month plan",
    interestFree: false,
    description: "Our lowest monthly instalment, ideal for higher-value devices.",
  },
];

// ── FAQ ────────────────────────────────────────────────────────
export const FAQS: FaqItem[] = [
  {
    id: "faq1",
    category: "Buying",
    question: "What does each condition grade actually mean?",
    answer:
      "Pristine means no visible wear under close inspection. Excellent means minor signs of use only visible in direct light. Good means light, visible wear that doesn't affect performance. Fair means clearly used but fully functional and tested. Every grade is assigned by our technicians against a written checklist, never by guesswork.",
  },
  {
    id: "faq2",
    category: "Buying",
    question: "Are your devices unlocked?",
    answer:
      "Yes. Every device we sell is network-unlocked and free of iCloud, Google or Samsung account locks before it's listed for sale.",
  },
  {
    id: "faq3",
    category: "Buying",
    question: "Do devices come with accessories?",
    answer:
      "Each listing shows exactly what's included — usually a charging cable and our certified packaging. Power adapters are included only where the original device shipped with one.",
  },
  {
    id: "faq4",
    category: "Warranty & Repairs",
    question: "What does the 30-day warranty cover?",
    answer:
      "Any functional fault not caused by accidental damage — battery, charging, buttons, cameras, connectivity and display issues are all covered for free repair, replacement or refund within 30 days of delivery.",
  },
  {
    id: "faq5",
    category: "Warranty & Repairs",
    question: "Can I book a repair for a device I didn't buy from you?",
    answer:
      "Yes, our repair service is open to any iPhone, Samsung Galaxy, iPad, Apple Watch or MacBook, regardless of where it was purchased.",
  },
  {
    id: "faq6",
    category: "Trade-In & Selling",
    question: "How is my trade-in or sell quote calculated?",
    answer:
      "We start from a base market value for your exact model and storage, then adjust for cosmetic condition, battery health and functionality based on your answers. The quote you receive online is the price we honour once the device matches your description.",
  },
  {
    id: "faq7",
    category: "Trade-In & Selling",
    question: "What's the difference between trading in and selling?",
    answer:
      "Trade-in credit is applied directly to a purchase and typically values your device slightly higher. Selling pays you cash via bank transfer, usually within 24 hours of us receiving and inspecting the device.",
  },
  {
    id: "faq8",
    category: "Trade-In & Selling",
    question: "What if my device doesn't match the condition I described?",
    answer:
      "We'll always contact you with a revised quote before finalising anything. You're free to accept the new offer or have the device shipped back to you at no cost.",
  },
  {
    id: "faq9",
    category: "Delivery & Payment",
    question: "How long does nationwide delivery take?",
    answer:
      "Most orders arrive within 1–3 working days in major metros and 2–5 working days elsewhere in South Africa. You'll receive tracking as soon as your order is dispatched.",
  },
  {
    id: "faq10",
    category: "Delivery & Payment",
    question: "What payment methods do you accept?",
    answer:
      "We accept card payments, Instant EFT and financing plans through our South African payment partners, plus card payments internationally.",
  },
  {
    id: "faq11",
    category: "Delivery & Payment",
    question: "Is my payment secure?",
    answer:
      "Yes. All payments are processed through PCI-compliant payment gateways — we never see or store your full card details.",
  },
  {
    id: "faq12",
    category: "General",
    question: "Where are you based?",
    answer:
      "iConnect Pre-Owned operates online with fulfilment centres serving all nine provinces. Delivery is nationwide, door to door.",
  },
  {
    id: "faq13",
    category: "General",
    question: "Do you offer a money-back guarantee?",
    answer:
      "Yes — if a device isn't right for you, you can return it unused in its original condition within 30 days for a full refund.",
  },
];

// ── About / team ──────────────────────────────────────────────
export const TEAM: TeamMember[] = [
  {
    name: "Naledi Khumalo",
    role: "Founder & CEO",
    bio: "Started iConnect Pre-Owned in 2019 after years in mobile retail, convinced South Africans deserved a more transparent way to buy pre-owned tech.",
  },
  {
    name: "Ahmed Suleman",
    role: "Head of Device Certification",
    bio: "Leads the technician team behind our 60-point inspection process, refined over tens of thousands of certified devices.",
  },
  {
    name: "Lerato Dlamini",
    role: "Customer Experience Lead",
    bio: "Makes sure every trade-in, repair booking and support query gets a fast, honest answer from a real person.",
  },
  {
    name: "Marco Pienaar",
    role: "Operations & Logistics Manager",
    bio: "Runs the nationwide courier network that gets certified devices to your door in as little as one working day.",
  },
];

// ── Trade-in / Sell catalog ────────────────────────────────────
// Broader than the shop catalog on purpose — customers trade in older
// models we may not currently stock for sale.
export interface TradeInModel {
  model: string;
  baseValue: number;
}

export const TRADE_IN_CATALOG: Partial<Record<DeviceCategory, TradeInModel[]>> = {
  iPhone: [
    { model: "iPhone 15 Pro Max", baseValue: 14500 },
    { model: "iPhone 15", baseValue: 9500 },
    { model: "iPhone 14 Pro", baseValue: 10000 },
    { model: "iPhone 14", baseValue: 7500 },
    { model: "iPhone 13", baseValue: 5800 },
    { model: "iPhone 12", baseValue: 4200 },
    { model: "iPhone 11", baseValue: 2800 },
    { model: "iPhone SE (2nd/3rd Gen)", baseValue: 2000 },
  ],
  "Samsung Galaxy": [
    { model: "Galaxy S24 Ultra", baseValue: 13000 },
    { model: "Galaxy S23", baseValue: 7500 },
    { model: "Galaxy S22", baseValue: 5500 },
    { model: "Galaxy Z Flip 5", baseValue: 9000 },
    { model: "Galaxy A54", baseValue: 3500 },
  ],
  iPad: [
    { model: "iPad Pro 12.9\"", baseValue: 11000 },
    { model: "iPad Air", baseValue: 6500 },
    { model: "iPad (10th Gen)", baseValue: 4500 },
    { model: "iPad Mini", baseValue: 5000 },
  ],
  "Apple Watch": [
    { model: "Apple Watch Ultra", baseValue: 7500 },
    { model: "Apple Watch Series 9", baseValue: 4200 },
    { model: "Apple Watch Series 8", baseValue: 3400 },
    { model: "Apple Watch SE", baseValue: 2600 },
  ],
  AirPods: [
    { model: "AirPods Max", baseValue: 3800 },
    { model: "AirPods Pro (2nd Gen)", baseValue: 2300 },
    { model: "AirPods (3rd Gen)", baseValue: 1400 },
    { model: "AirPods (2nd Gen)", baseValue: 900 },
  ],
  MacBook: [
    { model: "MacBook Pro 14\" M3", baseValue: 17000 },
    { model: "MacBook Air M2", baseValue: 11000 },
    { model: "MacBook Pro 13\" M2", baseValue: 9500 },
    { model: "MacBook Air M1", baseValue: 7500 },
  ],
};

export const TRADE_IN_CATEGORIES = Object.keys(TRADE_IN_CATALOG) as DeviceCategory[];

export const INSPECTION_POINTS = [
  "Battery health & charging performance",
  "Screen, digitiser & True Tone / colour accuracy",
  "Front & rear cameras, flash and Face/Touch ID",
  "Speakers, microphones & haptics",
  "Wi-Fi, Bluetooth, cellular & GPS signal",
  "Buttons, ports & wireless charging coil",
  "Water-resistance seals (where applicable)",
  "Full data wipe & factory account removal",
];

// ── Mock orders (account + admin demo data) ───────────────────
import type { Order, CartItem, Address } from "@/lib/types";

const sampleAddress: Address = {
  fullName: "Lindiwe Mokoena",
  line1: "14 Baker Street",
  suburb: "Rosebank",
  city: "Johannesburg",
  province: "Gauteng",
  postalCode: "2196",
  phone: "082 555 0134",
};

function orderItem(product: Product, quantity = 1): CartItem {
  return {
    productId: product.id,
    slug: product.slug,
    name: product.name,
    price: product.price,
    condition: product.condition,
    storage: product.selectedStorage,
    color: product.selectedColor,
    quantity,
    gradient: product.gradient,
    category: product.category,
  };
}

function buildTrackingSteps(status: Order["status"], placedDaysAgo: number): Order["trackingSteps"] {
  const order: Order["status"][] = ["Processing", "Quality Check", "Dispatched", "Out for Delivery", "Delivered"];
  const statusIndex = order.indexOf(status);
  return order.map((s, i) => ({
    status: s,
    label: s,
    complete: i <= statusIndex,
    timestamp: i <= statusIndex ? daysAgoIso(placedDaysAgo - i) : null,
  }));
}

export const MOCK_ORDERS: Order[] = [
  {
    id: "ord_1",
    reference: "IC-88214",
    placedAt: daysAgoIso(2),
    status: "Dispatched",
    total: getProductBySlug("iphone-15-pro-max-256gb")!.price,
    items: [orderItem(getProductBySlug("iphone-15-pro-max-256gb")!)],
    trackingSteps: buildTrackingSteps("Dispatched", 2),
    shippingAddress: sampleAddress,
    courierTrackingNumber: "CG2988471ZA",
  },
  {
    id: "ord_2",
    reference: "IC-87990",
    placedAt: daysAgoIso(9),
    status: "Delivered",
    total: getProductBySlug("samsung-galaxy-z-flip-5-256gb")!.price + getProductBySlug("airpods-pro-2nd-gen-usb-c-case")!.price,
    items: [
      orderItem(getProductBySlug("samsung-galaxy-z-flip-5-256gb")!),
      orderItem(getProductBySlug("airpods-pro-2nd-gen-usb-c-case")!),
    ],
    trackingSteps: buildTrackingSteps("Delivered", 9),
    shippingAddress: sampleAddress,
    courierTrackingNumber: "CG2977213ZA",
  },
  {
    id: "ord_3",
    reference: "IC-87650",
    placedAt: daysAgoIso(21),
    status: "Delivered",
    total: getProductBySlug("macbook-pro-14-m3-512gb")!.price,
    items: [orderItem(getProductBySlug("macbook-pro-14-m3-512gb")!)],
    trackingSteps: buildTrackingSteps("Delivered", 21),
    shippingAddress: sampleAddress,
  },
];
